### ISSUE TITLE
AndroidLocalize is outdated

### ISSUE THREAD

**Issue by maxkeppeler** [Airsaid/AndroidLocalizePlugin#171]
I would be happy to pay a small fee for this plugin since I use it frequently. I hope that an update will be released soon because the context menu is not available anymore in the recent Android Studio versions.

**Comment by Airsaid** [comment]
Fixed in v4.0.0

**Comment by ramanveerji** [comment]
> Fixed in v4.0.0

still not visible on plugin homepage https://plugins.jetbrains.com/plugin/11174-androidlocalize

**Comment by Airsaid** [comment]
> > Fixed in v4.0.0
> 
> still not visible on plugin homepage https://plugins.jetbrains.com/plugin/11174-androidlocalize

Under review

**Comment by ramanveerji** [comment]
I tried to load the module manually but still when i clicked in translate to other languages, android localise was not started. 

> > > Fixed in v4.0.0
> > 
> > still not visible on plugin homepage https://plugins.jetbrains.com/plugin/11174-androidlocalize
> 
> Under review

**Comment by Airsaid** [comment]
> I tried to load the module manually but still when i clicked in translate to other languages, android localise was not started.
> 
> > > > Fixed in v4.0.0
> > > 
> > > 
> > > still not visible on plugin homepage https://plugins.jetbrains.com/plugin/11174-androidlocalize
> > 
> > 
> > Under review

You can open a new issue and provide more information.
